#Only for local testing. Will not be maintained actively.
version: "3"

services:
  nextcloud:
    build:
      context: .
      dockerfile: Dockerfile.local
    restart: unless-stopped
    ports:
      - 8080:80
    env_file:
      - .env
    volumes:
      - nextcloud:/var/www/html
      - ./src/config/schulcloud.config.php:/var/www/html/config/schulcloud.config.php
      # uncomment the following line if you want to develop the app
      - ./src/custom_apps/groupfoldersautomation:/var/www/html/custom_apps/groupfoldersautomation

  db:
    image: postgres:latest
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - db:/var/lib/postgresql/data
    cap_add:
      - SYS_NICE  # CAP_SYS_NICE

networks:
  default:
    external:
      name: schulcloudserver_schulcloud-server-network

volumes:
  db:
  nextcloud:

