#Only for local testing. Will not be maintained actively.
version: "3"

services:
  traefik:
    image: traefik:v2.6
    container_name: traefik
    restart: unless-stopped
    ports:
      - "8081:80"
      - "8080:8080"
    command:
      #- "--log.level=DEBUG"
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro

  onlyoffice:
    image: onlyoffice/documentserver
    container_name: onlyoffice
    volumes:
      - /app/onlyoffice/DocumentServer/logs:/var/log/onlyoffice
      - /app/onlyoffice/DocumentServer/data:/var/www/onlyoffice/Data
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.onlyoffice.rule=Host(`onlyoffice.localhost`)"
      - "traefik.http.routers.onlyoffice.entrypoints=web"

  nextcloud:
    build:
      context: .
      target: development
    container_name: nextcloud
    image: schulcloud/schulcloud-nextcloud/development
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - nextcloud:/var/www/html
      - ../schulcloud-nextcloud-app:/var/www/html/custom_apps/schulcloud:rw
      - ../NextcloudExtract:/var/www/html/custom_apps/extract:rw
    depends_on:
      - db
      - storage
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.nextcloud.rule=Host(`nextcloud.localhost`)"
      - "traefik.http.routers.nextcloud.entrypoints=web"

  storage:
    image: minio/minio:latest
    container_name: storage
    ports:
      - 9100:9000
      - 9101:9001
    env_file:
      - .env
    command: 'server /data --console-address ":9001"'
    volumes:
      - /var/data/minio:/data

  collabora:
    image: collabora/code
    container_name: collabora
    restart: unless-stopped
    environment:
      - domain=nextcloud.localhost
      - "extra_params=--o:ssl.enable=false --o:ssl.termination=true"
    cap_add:
      - MKNOD
    tty: true
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.collabora.rule=Host(`collabora.localhost`)"
      - "traefik.http.routers.collabora.entrypoints=web"

  createbuckets:
    image: minio/mc
    env_file:
      - .env
    depends_on:
      - storage
    entrypoint: >
      /bin/sh -c "
      /usr/bin/mc alias set myminio http://storage:9000 $MINIO_ROOT_USER $MINIO_ROOT_PASSWORD;
      /usr/bin/mc mb myminio/nextcloud;
      /usr/bin/mc policy set public myminio/nextcloud;
      exit 0;
      "

  db:
    image: postgres:latest
    restart: unless-stopped
    ports:
      - 5433:5432
    env_file:
      - .env
    volumes:
      - db:/var/lib/postgresql/data
    cap_add:
      - SYS_NICE  # CAP_SYS_NICE

volumes:
  db:
  nextcloud:
  storage:

networks:
  default:
    name: schulcloud-nextcloud-network
