#Only for local testing. Will not be maintained actively.
version: "3"

services:
  nextcloud:
    build:
      context: .
      target: test
    image: schulcloud/schulcloud-nextcloud/test
    restart: unless-stopped
    ports:
      - 8081:80
    env_file:
      - .env
    volumes:
      - nextcloud:/var/www/html
    depends_on:
      - db

  db:
    image: postgres:latest
    restart: unless-stopped
    ports:
      - 5434:5432
    env_file:
      - .env
    volumes:
      - db:/var/lib/postgresql/data
    cap_add:
      - SYS_NICE  # CAP_SYS_NICE

networks:
  default:
    name: schulcloudserver_schulcloud-server-network

volumes:
  db:
  nextcloud:

