#Only for local testing. Will not be maintained actively.
version: "3"

services:
  nextcloud:
    build:
      context: .
      target: development
    container_name: nextcloud
    image: schulcloud/schulcloud-nextcloud/development
    restart: unless-stopped
    ports:
      - 8080:80
    env_file:
      - .env
    volumes:
      - nextcloud:/var/www/html
      - ../schulcloud-nextcloud-app:/var/www/html/custom_apps/schulcloud:rw
      - ../NextcloudExtract:/var/www/html/custom_apps/extract:rw
    depends_on:
      - db
      - storage

  storage:
    image: minio/minio:latest
    container_name: storage
    ports:
      - 9100:9000
      - 9101:9001
    env_file:
      - .env
    command: 'server /data --console-address ":9001"'
    volumes:
      - /var/data/minio:/data

  collabora:
    image: collabora/code:latest
    container_name: collabora
    ports:
      - 9980:9980
    cap_add:
      - MKNOD
    environment:
      - 'extra_params=--o:ssl.enable=false'
      - username=admin
      - password=admin

  createbuckets:
    image: minio/mc
    env_file:
      - .env
    depends_on:
      - storage
    entrypoint: >
      /bin/sh -c "
      /usr/bin/mc alias set myminio http://storage:9000 $MINIO_ROOT_USER $MINIO_ROOT_PASSWORD;
      /usr/bin/mc mb myminio/nextcloud;
      /usr/bin/mc policy set public myminio/nextcloud;
      exit 0;
      "

  db:
    image: postgres:latest
    restart: unless-stopped
    ports:
      - 5433:5432
    env_file:
      - .env
    volumes:
      - db:/var/lib/postgresql/data
    cap_add:
      - SYS_NICE  # CAP_SYS_NICE

volumes:
  db:
  nextcloud:
  storage:

