#Only for local testing. Will not be maintained actively.
version: "3"

services:
  onlyoffice:
    image: onlyoffice/documentserver
    container_name: onlyoffice
    expose:
      - '80'
      - '443'
    volumes:
      - document_data:/var/www/onlyoffice/Data
      - document_log:/var/log/onlyoffice

  nextcloud:
    build:
      context: .
      target: development
    container_name: nextcloud
    image: schulcloud/schulcloud-nextcloud/development
    restart: unless-stopped
    expose:
      - '80'
    env_file:
      - .env
    volumes:
      - nextcloud:/var/www/html
      - ../schulcloud-nextcloud-app:/var/www/html/custom_apps/schulcloud:rw
      - ../NextcloudExtract:/var/www/html/custom_apps/extract:rw
    depends_on:
      - db
      - storage

  storage:
    image: minio/minio:latest
    container_name: storage
    ports:
      - 9100:9000
      - 9101:9001
    env_file:
      - .env
    command: 'server /data --console-address ":9001"'
    volumes:
      - /var/data/minio:/data

#  collabora:
#    image: collabora/code
#    container_name: collabora
#    restart: unless-stopped
#    environment:
#      - domain=nextcloud.localhost
#      - "extra_params=--o:ssl.enable=false --o:ssl.termination=true"
#    cap_add:
#      - MKNOD
#    tty: true
#    labels:
#      - "traefik.enable=true"
#      - "traefik.http.routers.collabora.rule=Host(`collabora.localhost`)"
#      - "traefik.http.routers.collabora.entrypoints=web"

  createbuckets:
    image: minio/mc
    env_file:
      - .env
    depends_on:
      - storage
    entrypoint: >
      /bin/sh -c "
      /usr/bin/mc alias set myminio http://storage:9000 $MINIO_ROOT_USER $MINIO_ROOT_PASSWORD;
      /usr/bin/mc mb myminio/nextcloud;
      /usr/bin/mc policy set public myminio/nextcloud;
      exit 0;
      "

  db:
    image: postgres
    restart: unless-stopped
    ports:
      - 5433:5432
    env_file:
      - .env
    volumes:
      - db:/var/lib/postgresql/data
    cap_add:
      - SYS_NICE  # CAP_SYS_NICE

  nginx:
    container_name: nginx
    image: nginx
    restart: always
    ports:
      - 9090:80
      - 9443:443
    volumes:
      - ./src/nginx.conf:/etc/nginx/nginx.conf
      - nextcloud:/var/www/html
    links:
      - onlyoffice
      - nextcloud
    depends_on:
      - onlyoffice
      - nextcloud

volumes:
  db:
  nextcloud:
  storage:
  # onlyoffice-document-server
  document_data:
  document_log:

networks:
  default:
    name: schulcloud-nextcloud-network
