#Only for local testing. Will not be maintained actively.
version: "3"

services:
  nextcloud:
    build:
      context: .
      target: development
    image: schulcloud/schulcloud-nextcloud/development
    restart: unless-stopped
    ports:
      - 8080:80
    env_file:
      - .env
    volumes:
      - nextcloud:/var/www/html
      - ./src/custom_apps/schulcloud:/var/www/html/custom_apps/schulcloud:rw
      - ../NextcloudExtract:/var/www/html/custom_apps/custom-extract:rw
    depends_on:
      - db

  db:
    image: postgres:latest
    restart: unless-stopped
    ports:
      - 5433:5432
    env_file:
      - .env
    volumes:
      - db:/var/lib/postgresql/data
    cap_add:
      - SYS_NICE  # CAP_SYS_NICE

networks:
  default:
    name: schulcloudserver_schulcloud-server-network

volumes:
  db:
  nextcloud:

