version: '3'
services:
  app:
    container_name: app-server
    image: nextcloud:fpm
    restart: always
    env_file:
      - .env
    expose:
      - '80'
      - '9000'
    volumes:
      - app_data:/var/www/html
  onlyoffice-document-server:
    container_name: onlyoffice-document-server
    image: onlyoffice/documentserver:latest
    restart: always
    expose:
      - '80'
      - '443'
    volumes:
      - document_data:/var/www/onlyoffice/Data
      - document_log:/var/log/onlyoffice
  nginx:
    container_name: nginx-server
    image: nginx
    restart: always
    ports:
      - 8081:80
      - 8443:443
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - app_data:/var/www/html

  db:
    image: postgres
    restart: unless-stopped
    ports:
      - 5433:5432
    env_file:
      - .env
    volumes:
      - db:/var/lib/postgresql/data
    cap_add:
      - SYS_NICE  # CAP_SYS_NICE

volumes:
  db:
  document_data:
  document_log:
  app_data:
