## values.yml (default https://github.com/nextcloud/helm/blob/master/charts/nextcloud/values.yaml) for helm nextcloud helm chart
## https://github.com/nextcloud/helm
image:
  repository: schulcloud/schulcloud-nextcloud/production
  tag: latest
  pullPolicy: IfNotPresent

lifecycle:
  postStartCommand: ["/bin/sh", "-c", "/usr/nextcloud/configure.sh > /usr/nextcloud/configure_output"]

nextcloud:
  host: nextcloud.kube.home
  username: admin
  password: admin
  #update: 0
  #containerPort: 8080
  datadir: /var/www/html/data

  strategy:
    type: Recreate

  ##
  ## Extra environment variables
  extraEnv:
    - name: INSTALL_PLUGINS
      value: "groupfolders theming_customcss"
    - name: ENABLE_PLUGINS
      value: "schulcloud extract theming user_oidc"
    - name: RUN_CONFIGURATION
      value: "True"
    - name: EXTERNAL_GIT_PLUGINS
      value: "https://github.com/hpi-schul-cloud/NextcloudExtract.git:extract:1.3.6 https://github.com/hpi-schul-cloud/schulcloud-nextcloud-app.git:schulcloud:0.1.7"
    - name: EXTERNAL_ARCHIVE_PLUGINS
      value: "https://github.com/hpi-schul-cloud/user_oidc/releases/download/v1.3.0-alpha/user_oidc-v1.3.0-alpha.tar.gz:user_oidc"
    - name: DISABLE_PLUGINS
      value: "accessibility activity circles comments contactsinteraction dashboard files_sharing firstrunwizard password_policy photos privacy nextcloud_announcements recommendations sharebymail sociallogin support survey_client systemtags theming notifications updatenotification user_ldap user_status weather_status"
    - name: CONFIG_JSON
      value: '{"system": {
                "auto_logout": false,
                "remember_login_cookie_lifetime": "0",
                "session_lifetime": "7200",
                "session_keepalive": false,
                "upgrade.disable-web": true,
                "trashbin_retention_obligation": "7,7",
                "filelocking.enabled": false,
                "social_login_auto_redirect": false,
                "templatesdirectory": "",
                "skeletondirectory": "",
                "profile.enabled": false,
                "auth.webauthn.enabled": false,
                "allow_user_to_change_display_name": false,
                "config_is_read_only": false,
                "app_install_overwrite": [
                  "gluusso",
                  "schulcloud",
                  "extract"
                ],
                "user_oidc": {
                     "single_logout": false
                },
                "debug": true
              },
              "apps": {
                "core": {
                  "shareapi_default_permission_cancreate": "no",
                  "shareapi_default_permission_canupdate": "no",
                  "shareapi_default_permission_candelete": "no",
                  "shareapi_default_permission_canshare": "no",
                  "shareapi_default_permissions": "1",
                  "shareapi_restrict_user_enumeration_full_match": "no",
                  "shareapi_allow_share_dialog_user_enumeration": "no",
                  "shareapi_allow_group_sharing": "no",
                  "shareapi_allow_resharing": "no",
                  "shareapi_allow_public_upload": "no",
                  "shareapi_allow_links": "no",
                  "shareapi_enabled": "no"
                },
                "files": {
                  "types": "filesystem",
                  "enabled": "yes",
                  "default_quota": "0 B"
                },
                "files_antivirus": {
                  "av_port": "3310",
                  "av_path": "\/usr\/bin\/clamscan",
                  "installed_version": "3.3.1",
                  "types": "filesystem,dav",
                  "enabled": "yes",
                  "av_cmd_options": "",
                  "av_infected_action": "only_log",
                  "av_stream_max_length": "26214400",
                  "av_max_file_size": "-1",
                  "av_socket": "\/var\/run\/clamav\/",
                  "av_mode": "daemon",
                  "av_host": "antivirus"
                },
                "schulcloud": {
                  "enabled": "yes",
                  "types": ""
                },
                "extract": {
                  "enabled": "yes",
                  "types": ""
                },
                "theming_customcss": {
                  "customcss": "#app-navigation:not(.vue) > ul > li#quota {\\n    display: none;\\n}\\n\\n#app-navigation:not(.vue) > ul > li.nav-recent { \\n    display: none;\\n}\\n\\n#contactsmenu { display: none; }\\n\\n#app-settings-content:not(.vue) > label, #webdavurl, em  { \\n     display: none;\\n}\\n\\n[data-id=\"settings\"] { display: none; }\\n\\n[data-id=\"help\"] { display: none; }",
                  "cachebuster": "1659944778758",
                  "installed_version": "1.11.0",
                  "types": "",
                  "enabled": "yes"
                },
                "user_oidc": {
                   "allow_multiple_user_backends": "0",
                   "userinfo_bearer_validation": "false",
                   "selfencoded_bearer_validation": "true",
                   "types": "authentication",
                   "enabled": "yes",
                   "provider-1-mappingQuota": "",
                   "provider-1-extraClaims": "",
                   "provider-1-jwksCache": "",
                   "provider-1-jwksCacheTimestamp": "",
                   "provider-1-uniqueUid": "0",
                   "provider-1-checkBearer": "1",
                   "provider-1-bearerProvisioning": "1",
                   "provider-1-mappingUid": "sub",
                   "provider-1-mappingDisplayName": "name",
                   "provider-1-mappingEmail": "email",
                   "provider-1-mappingGroups": "groups",
                   "provider-1-groupProvisioning": "1",
                   "provider-1-providerBasedId": "1",
                   "id4me_enabled": "0"
                 }
              }
            }'
    - name: POST_CONFIG_COMMAND
      value: 'sudo -u www-data PHP_MEMORY_LIMIT=512M php occ user_oidc:provider SchulcloudNextcloud --clientid="Nextcloud" --clientsecret="Nextcloud" --check-bearer="1" --unique-uid="0" --scope="openid offline profile email groups" --discoveryuri="http://hydra.localhost:9000/.well-known/openid-configuration"'
    # default is 512M
    - name: PHP_MEMORY_LIMIT
      value: '3458M'
    - name: OBJECTSTORE_S3_BUCKET
      value: 'nextcloud'
    - name: OBJECTSTORE_S3_KEY
      value: 'admin12345'
    - name: OBJECTSTORE_S3_SECRET
      value: 'admin12345'
    - name: OBJECTSTORE_S3_HOST
      value: 'storage'
    - name: OBJECTSTORE_S3_PORT
      value: '9000'
    - name: OBJECTSTORE_S3_AUTOCREATE # does not work local
      value: 'false'
    - name: OBJECTSTORE_S3_SSL
      value: 'false'
    # some s3 provider needs the following
    - name: OBJECTSTORE_S3_USEPATH_STYLE
      value: 'true'
    - name: OBJECTSTORE_S3_LEGACYAUTH
      value: 'true'
    - name: OBJECTSTORE_S3_REGION
      value: 'de-central'
    # https://github.com/nextcloud/docker/blob/master/.config/redis.config.php
    - name: REDIS_HOST
      value: cache
    - name: REDIS_HOST_PASSWORD
      value: redis12345
    - name: THEMING_NAME
      value: Schulcloud Nextcloud
    - name: THEMING_URL
      value: https://nextcloud-nbc.dbildungscloud.dev/
    - name: THEMING_SLOGAN
      value: Niedersächsische Bildungscloud
    - name: THEMING_COLOR
      value: '"#5083C7"'
    - name: THEMING_LOGO_URL
      value: https://niedersachsen.cloud/images/logo/logo-wt.png

internalDatabase:
  enabled: false

##
## External database configuration
##
externalDatabase:
  enabled: true
  ## Supported database engines: mysql or postgresql
  type: postgresql
  ## Database host
  host: postgresql.kube.home
  ## Database user
  user: nextcloud
  ## Database password
  password: nextcloud
  ## Database name
  database: nextcloud

###
### PostgreSQL chart configuration
### for more options see https://github.com/bitnami/charts/tree/master/bitnami/postgresql
###
postgresql:
  enabled: true
  global:
    postgresql:
      auth:
        username: nextcloud
        password: nextcloud
        database: nextcloud

service:
  type: ClusterIP
  port: 8080
  loadBalancerIP: nil
  nodePort: nil
