version: '3'
services:
  app:
    container_name: app-server
    image: nextcloud:fpm
    restart: always
    environment:
      - POSTGRES_DB=nextcloud
      - POSTGRES_USER=nextcloud
      - POSTGRES_PASSWORD=nextcloud
      - POSTGRES_HOST=db
      - NEXTCLOUD_ADMIN_USER=admin
      - NEXTCLOUD_ADMIN_PASSWORD=admin
    expose:
      - 80
      - 9000
    volumes:
      - app_data:/var/www/html
    depends_on:
      - db

  onlyoffice-document-server:
    container_name: onlyoffice-document-server
    image: onlyoffice/documentserver:latest
    restart: always
    expose:
      - 80
      - 443
    volumes:
      - document_data:/var/www/onlyoffice/Data
      - document_log:/var/log/onlyoffice

  collabora:
    image: collabora/code
    container_name: collabora
    restart: unless-stopped
    ports:
      - 127.0.0.1:9980:9980
    expose:
      - 80
      - 9980
    environment:
      - aliasgroup1=app-server
      - extra_params=--o:ssl.enable=false --o:ssl.termination=false
    cap_add:
      - MKNOD
    tty: true

  nginx:
    container_name: nginx-server
    image: nginx
    restart: always
    ports:
      - 9090:80
      - 9443:443
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - app_data:/var/www/html

  db:
    image: postgres
    restart: unless-stopped
    ports:
      - 5433:5432
    environment:
      - POSTGRES_DB=nextcloud
      - POSTGRES_USER=nextcloud
      - POSTGRES_PASSWORD=nextcloud
      - POSTGRES_HOST=db
    volumes:
      - db:/var/lib/postgresql/data
    cap_add:
      - SYS_NICE  # CAP_SYS_NICE

volumes:
  db:
  document_data:
  document_log:
  app_data:
