version: '3'
services:
  app:
    container_name: app-server
    image: nextcloud:fpm
    restart: always
    environment:
      - NEXTCLOUD_ADMIN_USER=admin
      - NEXTCLOUD_ADMIN_PASSWORD=admin
    expose:
      - '80'
      - '9000'
    volumes:
      - app_data:/var/www/html
  onlyoffice-document-server:
    container_name: onlyoffice-document-server
    image: onlyoffice/documentserver:latest
    restart: always
    expose:
      - '80'
      - '443'
    volumes:
      - document_data:/var/www/onlyoffice/Data
      - document_log:/var/log/onlyoffice
  collabora:
    image: collabora/code
    container_name: collabora
    restart: unless-stopped
    expose:
      - '80'
      - '9980'
    environment:
      - aliasgroup1=app-server
      - VIRTUAL_HOST=collabora.localhost
      - VIRTUAL_PORT=9980
      - "extra_params=--o:ssl.enable=false"
    cap_add:
      - MKNOD
    tty: true
  nginx:
    container_name: nginx-server
    image: jwilder/nginx-proxy
    restart: always
    ports:
      - 8081:80
      - 8443:443
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - app_data:/var/www/html

volumes:
  db:
  document_data:
  document_log:
  app_data:
