---
- name: Delete Namespace
  hosts:
    - sc-dev-nextcloud
  connection: local
  roles:
  - kubeconfig
  tasks:
  - name: Namespace
    kubernetes.core.k8s:
      name: "{{ namespace }}"
      kind: Namespace
      state: absent
      kubeconfig: "{{ kubeconfig }}"
      api_version: v1
