---
- name: Delete Namespace and Bucket
  hosts:
    - sc-dev-nextcloud
  connection: local
  roles:
  - kubeconfig
  tasks:

  - name: Delete s3 bucket
    amazon.aws.aws_s3:
      aws_access_key: "{{ s3_access_key }}"
      aws_secret_key: "{{ s3_access_secret }}"
      bucket: "{{ s3_bucket_name }}"
      mode: delete
      s3_url: "{{ s3_url_berlin }}"
      region: "{{ s3_region_berlin }}"
    when:  namespace !=  "nbc-main"

  - name: Delete Namespace
    kubernetes.core.k8s:
      name: "{{ namespace }}"
      kind: Namespace
      state: absent
      kubeconfig: "{{ kubeconfig }}"
      api_version: v1
    when:  namespace !=  "nbc-main"
