---
- name: Nextcloud Deployment
  hosts:
    - sc-dev-nextcloud
  connection: local
  roles:
  - kubeconfig
  tasks:
  - name: Add nextcloud chart repo
    kubernetes.core.helm_repository:
      name: nextcloud
      repo_url: "https://nextcloud.github.io/helm/"

  - name: Create a namespace based on branch
    kubernetes.core.k8s:
      name: "{{ namespace }}"
      kind: Namespace
      state: present
      kubeconfig: "{{ kubeconfig }}"
      api_version: v1
    when:  namespace !=  "nbc-main"

  - name: Create s3 bucket
    amazon.aws.aws_s3:
      aws_access_key: "{{ s3_access_key }}"
      aws_secret_key: "{{ s3_access_secret }}"
      bucket: "{{ namespace }}"
      mode: create
      s3_url: "{{ s3_url_berlin }}"
      region: "{{ s3_region_berlin }}"
    when:  namespace !=  "nbc-main"

  - name: Create Nextcloud instances
    include_tasks: multi-instance-nextcloud.yml
    vars:
      instance_vault: "{%if item.vault is defined%}{{item.vault}}{%else%}{{project}}-{{stage}}-{{item.name}}{%endif%}"
    loop: "{{ nextcloud_instances | selectattr('nextcloud_enabled', 'defined' ) | selectattr('nextcloud_enabled', 'equalto', true)}}"
    tags:
      - nextcloud

  - name: Create nextcloud-background-job configmap
    kubernetes.core.k8s:
      state: present
      kubeconfig: "{{ kubeconfig }}"
      definition:
        apiVersion: v1
        kind: ConfigMap
        metadata:
          name: background-job-script
          namespace: "{{ item.namespace }}"
        data:
          cron-script: |-
            #!/bin/bash
            # install kubectl
            set -e
            {{ get_kubectl_command }}
            kubectl version
            # run background job
            kubectl exec $(kubectl get pods -n {{ item.namespace }}| egrep "^nextcloud-[a-z0-9]{5,10}-[a-z0-9]{3,5}[^a-z0-9]") -- sudo -u www-data PHP_MEMORY_LIMIT=512M php -f /var/www/html/cron.php && echo "end of php -f /var/www/html/cron.php"
            echo "Background Job - Cron has been run!"
    tags:
      - nextcloud
      - nextcloud-cron
    loop: "{{ nextcloud_instances | selectattr('nextcloud_enabled', 'defined' ) | selectattr('nextcloud_enabled', 'equalto', true)}}"

  - name: Install nextcloud background job cron cronjob
    kubernetes.core.helm:
      name: nextcloud-cron
      chart_ref: "{{ playbook_dir }}/../charts/cronjob"
      wait: yes
      chart_version: "{{ nextcloud_background_job_chart_version }}"
      kubeconfig: "{{ kubeconfig }}"
      release_namespace: "{{ item.namespace }}"
      values:
        "{{ nextcloud_background_job_chart_values }}"
    tags:
      - nextcloud
      - nextcloud-cron
    loop: "{{ nextcloud_instances | selectattr('nextcloud_enabled', 'defined' ) | selectattr('nextcloud_enabled', 'equalto', true)}}"
