---
- name: Nextcloud Deployment
  hosts:
    - sc-dev-nextcloud
  connection: local
  roles:
  - kubeconfig
  tasks:
  - name: Add nextcloud chart repo
    kubernetes.core.helm_repository:
      name: nextcloud
      repo_url: "https://nextcloud.github.io/helm/"

  - name: Create a namespace based on branch
    kubernetes.core.k8s:
      name: "{{ namespace }}"
      kind: Namespace
      state: present
      kubeconfig: "{{ kubeconfig }}"
      api_version: v1

  - name: Create Nextcloud instances
    include_tasks: multi-instance-nextcloud.yml
    vars:
      instance_vault: "{%if item.vault is defined%}{{item.vault}}{%else%}{{project}}-{{stage}}-{{item.name}}{%endif%}"
    loop: "{{ nextcloud_instances | selectattr('nextcloud_enabled', 'defined' ) | selectattr('nextcloud_enabled', 'equalto', true)}}"
    tags:
      - nextcloud

# s3 bucket  nextcloud-aimee-test in frankfurt

# wenn ingress da ist, dann aber im Helm Chart disabled, wird der Ingress gelöscht? 
# -  Login wird redirected auf die dev-nbc-Seite, die brauch ein Eintrag im SHD, dass man zugreifen darf
# auch metriken testen

