name: Deploy Nextlcoud on Branch namespace
# testen später ob main wirklich nicht ausgerollt wird
# on: push
  # push:
  #   branches:
  #   - "!main"
# gh workflow run <workflow> --ref <branch-name> -f <myparameter>=<myvalue>
on:
  workflow_dispatch:
    inputs:
      BRANCH_NAME_SCHULCLOUD_INSTANCE:
        description: 'Branch name of schulcloud instance of sc-dev-devcenter-1'
        required: true

jobs:
  get_branch_name:
    runs-on: ubuntu-latest
    outputs:
      branch: ${{ steps.extract_branch.outputs.branch }}
    steps:
      - name: Extract branch name
        shell: bash
        run: |
          branch_name=$(echo "branch=${GITHUB_REF#refs/heads/}")
          echo "branch_name=${GITHUB_REF#refs/heads/}" >> $GITHUB_ENV

          namespace_name=$(echo $branch_name | sed 's@.*/@@' | tr [A-Z] [a-z] | tr _ - | tr \. -)
          echo "before regex:" $branch_name "after regex:" $namespace_name
          echo "$namespace_name" >> $GITHUB_OUTPUT
        id: extract_branch

  deploy_nextcloud_from_branch:
    if: ${{ needs.get_branch_name.outputs.branch }} != 'main'
    needs:
      - get_branch_name
    uses: ./.github/workflows/deploy-nextcloud.yml
    with:
      HOST: sc-dev-nextcloud
      NAMESPACE:  ${{ needs.get_branch_name.outputs.branch }}
      BRANCH_NAME_SCHULCLOUD_INSTANCE: ${{ inputs.BRANCH_NAME_SCHULCLOUD_INSTANCE }}
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}
      KUBECONFIG: ${{ secrets.KUBECONFIG }}
      SOCIALLOGINCLIENTID: ${{ secrets.SOCIALLOGINCLIENTID }}
      SOCIALLOGINSECRET: ${{ secrets.SOCIALLOGINSECRET }}
