---
name: Nextcloud Ansible Playbook Action

on:
  workflow_call:
    inputs:
      NAMESPACE:
        required: true
        type: string
      HOST:
        required: true
        type: string
    secrets:
      token:
        required: true
      KUBECONFIG:
        required: true

jobs:
  run_ansible_playbook_nextcloud:
    environment: "{{ inputs.HOST }}"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v1

      - name: Install requirements python3
        shell: bash
        run: |
          python3 -m pip install kubernetes

      - name: install requirements ansible-galaxy
        run: ansible-galaxy install -r ansible/collections/requirements.yml

      - name: Create Kubeconfig file in config folder
        working-directory: ${{ github.workspace }}/ansible/roles/kubeconfig
        run: |
          mkdir files
          echo "${{ secrets.KUBECONFIG }}" > files/config

      - name: Set ENVs in config.yml file
        working-directory: ${{ github.workspace }}/ansible/group_vars
        run: |
          echo -e "\nnamespace: ${{ inputs.NAMESPACE }}" >> config.yml
          cat config.yml

      - name: Execute Ansible Nextcloud Playbook
        working-directory: ${{ github.workspace }}/ansible
        run: ansible-playbook ./nextcloud-playbook.yml --inventory-file hosts -e 'ansible_python_interpreter=/usr/bin/python3' -v -l ${{ inputs.HOST }}

      - name: Delete config files
        if: always()
        working-directory: ${{ github.workspace }}/ansible/roles/kubeconfig
        run: rm -rf /config





