name: Deploy Nextcloud on nbc-main
on:
  push:
  # workflow_dispatch:
  # push:
  #   branches:
  #     - main

jobs:
  nextcloud_approval:
    environment: approve_sc_dev_nextcloud
    runs-on: ubuntu-latest
    steps:
      - run: echo "Approval from authorized approve_sc_dev_nextcloud Group has been given!"

  deploy_nextcloud_from_main:
    needs:
      - get_branch_name
    uses: ./.github/workflows/deploy-nextcloud.yml
    with:
      CLUSTER: "sc-dev-nextcloud"
      BUCKET_NAME: "sc-dev-cd-nextcloud-txl-bucket-0000"
      NAMESPACE: "nbc-main"
      NAMESPACE_SCHULCLOUD_INSTANCE: "nbc-main"
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}
      KUBECONFIG: ${{ secrets.KUBECONFIG }}