# Discuss whether we have use case or not
# Test this at the end
name: Deploy Nextlcoud
on: push
  branches:
    - main

jobs:
  nextcloud_approval:
    environment: approve_sc_dev_nextcloud
    runs-on: ubuntu-latest
    steps:
      - run: echo "Approval from authorized approve_sc_dev_nextcloud Group has been given!"

# Bucket value muss normal sein
  deploy_nextcloud_from_main:
  if: ${{ needs.get_branch_name.outputs.branch }} == 'main'
    needs:
      - get_branch_name
      # must change
    uses: ./.github/workflows/dev-nextcloud.yml
    with:
      HOST: sc-dev-nextcloud
      NAMESPACE: nbc-main
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}
      KUBECONFIG: ${{ secrets.KUBECONFIG }}