name: Deploy Nextlcoud
on: push
# wähle den Branch aus 
  # workflow_dispatch:
  #   inputs:
  #     NAMESPACE:
  #       description: "Select Edusharing cluster"
  #       required: false
        # default: all

jobs:
  # nextcloud_approval:
  #   environment: approve_sc_dev_nextcloud
  #   runs-on: ubuntu-latest
  #   steps:
  #     - run: echo "Approval from authorized approve_sc_dev_nextcloud Group has been given!"

  get_branch_name:
    # needs:
    #   - nextcloud_approval
    runs-on: ubuntu-latest
    outputs:
      branch: ${{ steps.extract_branch.outputs.branch }}
    steps:
      - name: Extract branch name
        shell: bash
        run: echo "branch=${GITHUB_REF#refs/heads/}" >> $GITHUB_OUTPUT
        # not sure if this is necessary
        # id: extract_branch

  deploy_nextcloud:
    needs:
      - get_branch_name
    uses: ./.github/workflows/dev-nextcloud.yml
    with:
      HOST: sc-dev-nextcloud
      NAMESPACE:  ${{ needs.get_branch_name.outputs.branch }}
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}
      KUBECONFIG: ${{ secrets.KUBECONFIG }}