name: Publish Image to Docker

on:
  push:
    tags:
      - "[0-9]*"

jobs:
  publish_production_image:
    name: "Publish production image"
    permissions:
      packages: write
      security-events: write
      contents: read
    uses: dBildungsplattform/dbp-github-workflows/.github/workflows/image-publish-trivy.yaml@7
    with:
      image_name: "schulcloud-nextcloud"
      run_trivy_scan: false
      image_tag_generation: 'mmp_git_tag,mm_git_tag'
      add_latest_tag: true
      container_registry: "ghcr.io"
      target: "production"

  publish_development_image:
    name: "Publish development image"
    permissions:
      packages: write
      security-events: write
      contents: read
    uses: dBildungsplattform/dbp-github-workflows/.github/workflows/image-publish-trivy.yaml@7
    with:
      image_name: "schulcloud-nextcloud/dev"
      run_trivy_scan: false
      image_tag_generation: 'mmp_git_tag,mm_git_tag'
      add_latest_tag: true
      container_registry: "ghcr.io"
      target: "development"
